import { StyleSheet } from 'react-native';

export const homeStyles = StyleSheet.create({
  scroll: { flexGrow: 1 },
  headerBanner: { width: '100%' },
  headerRow: { flexDirection: 'row', alignItems: 'center' },
  greeting: { fontWeight: '400' },
  balanceCard: { overflow: 'hidden' },
  accountRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 4,
  },
  accountId: { fontWeight: '400', color: '#FFFFFF' },
  balanceRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  balanceText: { fontWeight: '500', color: '#FFFFFF' },
  cardBtnsRow: { flexDirection: 'row' },
  cardBtn: {
    flex: 1,
    borderWidth: 1,
    borderRadius: 8,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 4,
  },
  cardBtnText: { fontWeight: '400' },
  quickActionsRow: { flexDirection: 'row' },
  quickBtn: {
    flex: 1,
    height: 35,
    borderRadius: 75,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  quickBtnText: { fontWeight: '400' },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
  },
  sectionTitle: { fontWeight: '500' },
  sectionSub: { fontWeight: '400', marginTop: 2 },
  viewAll: { fontWeight: '400' },
  budgetAddBtn: {
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  transactionsEmpty: { alignItems: 'center', justifyContent: 'center' },
  emptyText: { fontWeight: '400' },
});
